env:
  global:
  - SH=bash
  matrix:
  - secure: iByHDqsyeyvqievXU6ZAxu4n/02PL9remM/7yWDHPwtrt/QPXjdScsASFGTTuaPYxqVeP1EypiEs9l9iZD5Rt0dWODB5/ex557pfo4EwMZq/Yr3sEtXvw3gEQWB92k3zSV4ksFCakNlxSuylomPreCKiCwW2we9q/UbSAxHkd23jj7fH3gy72wU8NVnK7/5sy7rV7P2GLr2T8hRzeLjBuixlpvcnbqS1niE7V4mZ19dbFZcqdj+ip/YpyJTKl8bhXPeS7cYRbhU3j0/XsftPVi7WusQO2CljK47JPE1XdYbgq1utEI8hMlsef1y3q2nir847FylCJUNVl7QVybUHF5ykhM1hOm0UhggF5KQZtY2vAGrKsmDPWCWQgdxE6M5Skun8Sm9z60e3qV2IiaKv1GHZ8d6ve5IxXXbQA99iz/AhJZT6bG1BOMRrnEMHW6fTrb02mWWxT6nyLlS2hbmgMB6TBG+Xnb5nu10shIvSg0Zuptvg7kHIEY89MiOUYxbpbFSCNHE8OFSAkeG/W8nllSvni9b3YHDQzkBx/zBDNM9TKDJmuW1CLdavvUgtJDuZE+O91ytTZ/kHyjNbO2mCIOWsA7qkAHklgXqa3wx/GzbJOQ4nRw/NyVyzOb3b3gGy+5DsDS6qdE2Tk85VyKysw7YDlfi8LA3Q0YT/XF2B9/Y=
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install graphicsmagick
  imagemagick -y; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick; fi
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm uninstall aws-sdk
- SETTINGS=$SETTINGS npm test
- npm install --save aws-sdk
- SETTINGS=$SETTINGS npm test
os:
- linux
- osx
